### ISSUE TITLE
Silent crash in float_endf

### ISSUE THREAD

**Issue by aidancrilly** [paulromano/endf-python#6]
Hi,

Firstly, thanks for this tool - I am working on using it in my project NeSST (https://github.com/aidancrilly/NeSST).

I just wanted to document this issue I had. Some details, this occurred on a Windows machine, installed without error using pip and MSVC 2022. I could import the library but loading any endf file would silently crash. I suspected this was the pybind'ed C++ so I swapped from using float_endf from the C++ to the py_float_endf. The code then ran without crashing.

Is there a reason to use the C++ version over the python version?

**Comment by paulromano** [comment]
Hi @aidancrilly! The C++/pybind-ed version is there mostly for performance reasons. If you load a very large ENDF file (or try to parse an entire library), it can make a big difference in performance. If that's not a concern to you though, you should be fine with the Python version. I'll give it a go on Windows to see if I can reproduce the behavior you're seeing. If possible, could you point me to an ENDF file you were having trouble with?

**Comment by aidancrilly** [comment]
Thanks for taking a look, it was the FENDL-3.2b (https://www-nds.iaea.org/fendl/) ENDF file for deuterium

**Comment by aidancrilly** [comment]
@paulromano 

Perhaps should be a separate issue but using the python endf float converter - this also seems to have problems with files from the BROND library. In particular the tritium file (https://www-nds.iaea.org/exfor/servlet/E4sGetEvaluation?EvalID=118505&req=16765) has zero floats as 0.0    + 0, which trips up the RE. 

I swapped to this solution which seems to work for normal ENDF format and this anomaly:

```python3
def py_float_endf(input_str : str) -> float:
    # Define the regular expression pattern to match numbers without 'e'
    pattern = r'([-+]?\d*\.\d+|\d+)\s*([-+])\s*(\d+)'

    # Function to replace the matched patterns with exponential notation
    def replace(match):
        num = float(match.group(1))
        sign = match.group(2)
        exp = int(match.group(3))
        return f"{num}e{sign}{exp}"

    # Use re.sub() to replace matched patterns with exponential notation
    result = float(re.sub(pattern, replace, input_str))
    return result
```

Happy to stick in PR if interested
